### ISSUE TITLE
Repository not private

### ISSUE THREAD

**Issue by ckchmod** [uwhpsc-2016/homework3#1]
I don't think the homework repositories are private. I can see other people's.

**Comment by crispc85** [comment]
Same, my homework 3 repo is public, and I see other students' repos on the main uwhpsc-2016 page.

**Comment by alyfarahat** [comment]
Same here.

**Comment by mladenze** [comment]
yup

**Comment by gmikel** [comment]
Confirmed. I was just about to send an email before I noticed the individual homework3 repo. 

I'm going to hold off on creating my repo for now.

**Comment by cswiercz** [comment]
New link is posted. Thank you everyone for noticing.
