### ISSUE TITLE
Running ctests

### ISSUE THREAD

**Issue by natwall27** [uwhpsc-2016/homework3#17]
I am getting an error when trying to run ctests. I have made sure to pull the corrections to my private repo, and followed what we did in the last homework. Here is what I have tried:

gcc ctests/example.c -Llib -lhomework3 -Iinclude -Wl,-rpath,./lib -lm -o example

Here is the error I am getting:

/usr/bin/ld: /tmp/ccGeZo8U.o: undefined reference to symbol 'omp_get_wtime@@OMP_2.0'
/usr/lib/x86_64-linux-gnu/libgomp.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Any suggestion on how I should run ctests differently? Thank you.

**Comment by quantheory** [comment]
You have to add the `-fopenmp` flag when compiling. It may have to be one of the first arguments; I can't recall.

**Comment by natwall27** [comment]
Yep, that fixed it. Thank you, Sean!
