### ISSUE TITLE
calling functions from integrate.h

### ISSUE THREAD

**Issue by natwall27** [uwhpsc-2016/homework3#22]
I made a ctest for trapz_serial, "test_trapz_serial", where the function was included in the test, and got a reasonable approximation to pi when running the test. When I run example.c, I do not get a reasonable approximation for pi. I have tried:

1) Copy-paste function trapz_serial to make sure it is exactly the same, compiling and running. 

This got me the same results before: reasonable approximation for pi in test_trapz_serial,-0.000100, in example.c. 

2) Removing the function trapz_serial from within  test_trapz_serial  and inserting "#integrate.h". 
3) Recompiling integrate.c

This also gave the same unreasonable approximation for pi in both ctests/test_trapz_serial and  ctests./example.

4) Adding the function trapz_serial back into test_trapz_serial, compiling and running.

This got me the original results: reasonable approximation for pi in test_trapz_serial, -0.000100, in example.c. 

5) Adding to test_trapz_serial:
# include <math.h>
# include <stdio.h>
# include <stdlib.h>
# include <omp.h>

This also gave the same unreasonable approximation for pi in both ctests/test_trapz_serial and  ctests./example.

So, it seems to me the issue is in calling #integrate.h in the ctests. Here is what it looks like at the top of the tests:
# include <math.h>
# include <stdio.h>
# include <stdlib.h>
# include <omp.h>
# include "integrate.h"

Any ideas why I am getting different results from what calling integrate.h vs. writing the function above main in ctests?

**Comment by cswiercz** [comment]
Hmm...it's difficult to tell what is going on. Create a private issue. Make sure to update your GitHub repo so we can see the version you're working with. Also, please list the compile commands you're using when you create said issue.

**Comment by natwall27** [comment]
I do not know what I did, but it is working now. I have been using the same format from homework 2.
