### ISSUE TITLE
Debugging simps_parallel_chunked

### ISSUE THREAD

**Issue by natwall27** [uwhpsc-2016/homework3#24]
My `simps_parallel_chunked` function is not working for chunk sizes bigger than 1. I notice that the output sum decreases as chunk size increases.

Does anyone have suggestions for what to look for in debugging an issue like this? Thank you.

**Comment by cswiercz** [comment]
How did you deduce that `simps_parallel_chunked` isn't working?

**Comment by natwall27** [comment]
Sorry, I wrote that wrong. It was changing the number of threads that I had an issue with.

I tested python's function "simps" with my function "simps_parallel_chunked", and they agreed when thread_num= 1, but not for thread_num =2, 4, 8.  The output of simps_parallel_chunked decreased in values as number of threads increased.
