### ISSUE TITLE
Reobtain homework3 repository

### ISSUE THREAD

**Issue by mollyzyy787** [uwhpsc-2016/homework3#32]
I have accidentally merged the branch of my previous homework repository and homework3 repository. now my homework1 and 2 folders are all inside my homework3 repo, and the homework3 folder is somehow gone. and I try to clone it from the homework 3 public repo, and things get messier and messier. 

Is there anyway I can delete my current homework3 repo and get a new one? or is it possible to delete the last two commit I made? I tried git reverse and git rebase, ended up reversed the file in my SMC folder... so basically deleted file in my SMC, but my hw3 repo is still unchanged. :(

**Comment by bmva** [comment]
Someone correct me if I'm wrong...and I'm sure there are better ways to do this...but I believe you could do a git log to get the commit ID of your latest valid commit, then do a git checkout of this commit ie git checkout ...then do a git branch 118ea44de2ea17a3691135ed840cab3379be524f (but whatever your ID is)...and then do a git checkout -b newbranchwithouthw2...or whatever you want to call the branch.  Then you can start pushing that branch to your master.

**Comment by mollyzyy787** [comment]
Thank you I think I successfully reset my repo using git reset.  Thanks so much @bmva
